meta:
    site_title: "博客测试页面"
    site_subtitle: "人生就是修行"
    site_language: "zh-cn"
    absolute_baseurl: http://blog.webcb.net
    domain: webcb.net
    author:
        full_name:chenbing
        short_name: cb
        name: cb
        email: sphawkcn@gmail.com

url: http://blog.webcb.net

#baseurl: /base

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: ypchenstory

lsi: false



